[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
authors = ["Lawrence Bell"]

[[bin]]
name = "day_01"

[[bin]]
name = "day_02"

[[bin]]
name = "day_03"

[[bin]]
name = "day_04"

[dependencies]
nom = "7.1.3"
