packages: [.]
resolver: lts-19.33
extra-deps:
  - hedgehog-1.2
  - lens-5.2.3
  - linear-1.22
  - megaparsec-9.3.1
  - pretty-simple-4.1.2.0
  - tasty-hedgehog-1.4.0.1
  - vector-0.13.1.0
  - vector-algorithms-0.9.0.1
  - vector-stream-0.1.0.0
